### ISSUE TITLE
Analyze LESS files

### ISSUE THREAD

**Issue by 0x1AD2** [madebysource/lesshat#141]
Hi MadeBySource,

Is it possible to analyze/scan my **.less** files and see if there is any improvement for them using lesshat? For example using the CLI or something?

*lesshat analyse -path 'C:\projects\example-project\less\example.less'*

- replace transition by lesshat transition on line 120
- replace border-radius by lesshat border-radius on line 172

**Comment by petrbrzek** [comment]
This is not possible now. Feel free to send pull request.
