### ISSUE TITLE
Keyframes breaks Safari 10.11 and iOS9 beta

### ISSUE THREAD

**Issue by davipt** [madebysource/lesshat#156]
Duplicate from #139 and #129, just to make clear that
1. Safari 10.11 and iOS9 beta are breaking with this
2. the issue is not the extra semicolon at the last line (@keyframe), but the lack of the "}" closing it at the same line. 

So I added a closing "}", which means I need to create a dummy line to reopen "{".

**Comment by herrmannplatz** [comment]
Would be nice to have this fix in, as it also breaks code quality tools like csscss.

**Comment by twobit** [comment]
+1 causing problems for us too.

**Comment by GarikFF** [comment]
+1 head broke yesterday

**Comment by mboudreau** [comment]
This has been fixed in 4.0.1.
