### ISSUE TITLE
.keyframes-mixin and Safari 

### ISSUE THREAD

**Issue by GarikFF** [madebysource/lesshat#165]
Hello there!

I'm using .keyframes-mixin - http://take.ms/KanEU
But in the final CSS I getting wrong styles:
http://take.ms/YFWWd

As you can see it's extra semicolon. Because of this symbol in Safari does not connect all subsequent styles, cause it's wrong syntax, I suppose... or not? 

In other browsers, it works well, but Safari is very strict :-)  Is it my fault or mixin or Safari?

Safari 9.0 , OS X El Capitan

**Comment by GarikFF** [comment]
Duplicate :-(

**Comment by mboudreau** [comment]
This has been fixed in 4.0.1.
